---
title: "Causal Inference Final Code"
author: "Sam Neylon"
date: '2024-05-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(stringr)

set.seed(7008)

```

# Import

```{r }

# Import ln_emp_flood_df

ln_emp_flood_df <- read_csv(here("data/SHELDUS/ln_emp_flood_df.csv"),
                     col_types = cols(
  year = col_double(),
  st = col_character(),
  cty = col_character(),
  firms = col_double(),
  estabs = col_double(),
  emp = col_double(),
  denom = col_double(),
  estabs_entry = col_double(),
  estabs_entry_rate = col_double(),
  estabs_exit = col_double(),
  estabs_exit_rate = col_double(),
  job_creation = col_double(),
  job_creation_births = col_double(),
  job_creation_continuers = col_double(),
  job_creation_rate_births = col_double(),
  job_creation_rate = col_double(),
  job_destruction = col_double(),
  job_destruction_deaths = col_double(),
  job_destruction_continuers = col_double(),
  job_destruction_rate_deaths = col_double(),
  job_destruction_rate = col_double(),
  net_job_creation = col_double(),
  net_job_creation_rate = col_double(),
  reallocation_rate = col_double(),
  firmdeath_firms = col_double(),
  firmdeath_estabs = col_double(),
  firmdeath_emp = col_double(),
  FIPS_5 = col_character(),
  PropertyDmg = col_double(),
  PropertyDmg_Adj2022 = col_double(),
  PropertyDmgPerCapita_Adj2022 = col_double(),
  SHELDUS = col_double(),
  pre_96 = col_double(),
  serious_flood = col_double(),
  treatment = col_double(),
  first_hurr_year = col_double(),
  group = col_double(),
  ln_emp = col_double(),
  time_to_treat = col_double(),
  treat = col_double(),
  FIPS = col_double(),
  treatment_post = col_double()
))

```

# Variables

[Leave notes here on time to treat etc. even though these are already in the data you imported]

# Vanilla OLS

```{r }

ols.ln_emp.model <- lm(ln_emp ~ treatment_post, data = ln_emp_flood_df)

```

```{r }

summary(ols.ln_emp.model)

```

# fixest

```{r }

library(fixest)

```

## Model 1 - Averaged ATT

```{r }

feols_ln_emp.AvgATT <- feols(ln_emp ~ treatment_post | FIPS_5 + year, ln_emp_flood_df, cluster = "FIPS_5")

```

```{r }

summary(feols_ln_emp.AvgATT)

```

## Event Study - Time-varying ATT's

```{r }

feols_ln_emp.Event <- feols(ln_emp ~ i(time_to_treat, treat, ref = c(-1, -1000)) | FIPS_5 + year, ln_emp_flood_df, cluster = "FIPS_5")

```

### Summary

```{r }

summary(feols_ln_emp.Event)

```

### Figure X - Event Plot

```{r }

iplot(feols_ln_emp.Event)

```

# fect

```{r }

library(fect)
library(panelView)

```

## Model

```{r }

fect_ln_emp <- fect(ln_emp ~ treatment, 
                data = ln_emp_flood_df, 
                index = c("FIPS","year"),
                # force: include both unit and time effects
                force = "two-way",
                # Interactive Fixed Effects
                method = "ife", 
                # Cross-validation to pick number of factors
                CV = TRUE, 
                # Test between 0 and 5 factors
                r = c(0, 5), 
                se = TRUE, 
                nboots = 200, 
                parallel = TRUE,
                #cores = 4) # 4 for GC pc
                cores = 6) # 6 for home PC

```

## Summary

```{r }

print(fect_ln_emp)

```

### Plot

```{r }

plot(fect_ln_emp, main = "Estimated ATT (IFEct)")

```

```{r}

fect_ln_emp$est.att

```

# Appendix

## 'did' package

```{r eval=FALSE}

library(did)

```

```{r eval=FALSE}

ln_emp_1 <- att_gt(yname="ln_emp",
                  tname="year",
                  idname="FIPS",
                  gname="group",
                  data=ln_emp_flood_df,
                  control_group = "notyettreated")

```

```{r eval=FALSE}

  ln_emp_1_es <- aggte(ln_emp_1, type="dynamic")

```

```{r eval=FALSE}

  ggdid(ln_emp_1_es, xgap = 4)

```

```{r eval=FALSE}

summary(ln_emp_1_es)

```